### ISSUE TITLE
Recommended improvements on your leaderboard

### ISSUE THREAD

**Issue by katarighe** [mershark/Leaderboard#4]
Hi @mershark, 

The leaderboard is fantastic and well done. It functions everything as usual, as well as the API provided inside the app. ✅👏

However, there are some improvements that need to be considered in order to make the project spectacular. 🙌📝

- Add a header located on the bottom on the leaderboard saying that this is by you. 
- Separate equally the recent scores and the add your score section in order to make it better. 
- On the score list, it is better to shorten the size of each player as it also better, because it is a simple application where you simply put your name and score, there is no need to make the element very large. 

I hope this understands on this. Thank you 😊👋

**Comment by mershark** [comment]
Thanks
